AWSTemplateFormatVersion: "2010-09-09"
Description: Basic EC2 Instance

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageID: ami-056ee704806822732
      InstanceType: t2.micro
      KeyName: NGINX.pem
      SecurityGroups:
        -default
        - !Ref SSHSecurityGroup
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH Security Group
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: '0.0.0.0/0'